### ISSUE TITLE
请教学长

### ISSUE THREAD

**Issue by violet617** [miaochenxi/zzuli-autoclockin#3]
在这个地方报错，是我的base64编码没弄对吗？或者说是运行npm run encrypt后得到的base64编码是什么？
`> zzuli-autoclockin@1.5.1 action
> node ./src/action.js "--username" "--password" "--type" "0" "--data"

/home/runner/work/izzuli/izzuli/src/utils/crypto-js.js:868
                var base64StrLength = base64Str.length;
                                                ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Object.parse (/home/runner/work/izzuli/izzuli/src/utils/crypto-js.js:868:49)
    at /home/runner/work/izzuli/izzuli/src/action.js:10:39
    at Object.<anonymous> (/home/runner/work/izzuli/izzuli/src/action.js:38:2)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.3.1
Error: Process completed with exit code 1`

**Comment by miaochenxi** [comment]
> 在这个地方报错，是我的base64编码没弄对吗？或者说是运行npm run encrypt后得到的base64编码是什么？ `> zzuli-autoclockin@1.5.1 action
> 
> > node ./src/action.js "--username" "--password" "--type" "0" "--data"
> 
> /home/runner/work/izzuli/izzuli/src/utils/crypto-js.js:868 var base64StrLength = base64Str.length; ^
> 
> TypeError: Cannot read properties of undefined (reading 'length') at Object.parse (/home/runner/work/izzuli/izzuli/src/utils/crypto-js.js:868:49) at /home/runner/work/izzuli/izzuli/src/action.js:10:39 at Object. (/home/runner/work/izzuli/izzuli/src/action.js:38:2) at Module._compile (node:internal/modules/cjs/loader:1097:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10) at Module.load (node:internal/modules/cjs/loader:975:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) at node:internal/main/run_main_module:17:47
> 
> Node.js v17.3.1 Error: Process completed with exit code 1`


你的代码太老了没有更新，先克隆最新的代码，现在已经1.5.7了吧。

看报错可能是base64编码没有获取到：
- 先 `git pull` 更新一下项目，然后在本地打卡一次，然后运行 `npm run encrypt`，可以获取编码
- 如果用 GitHub Action 的话，检查编码是不是正确配置在了对应的secret里，HOMEINFO或者MORNINFO
