### ISSUE TITLE
求证

### ISSUE THREAD

**Issue by violet617** [miaochenxi/zzuli-autoclockin#4]
![image](https://user-images.githubusercontent.com/79788757/148956731-e0479c06-111b-4f24-9b9b-e37edb625c2a.png)
这样是不是就算成功了？

**Comment by miaochenxi** [comment]
可以点进去看一下输出，里面有一个链接可以查看一下是不是打卡成功。

**Comment by violet617** [comment]
> 可以点进去看一下输出，里面有一个链接可以看一下不是打卡成功。

感谢感谢
